<?php

	/**
	 * Dao Factory
	 * 
	 * @author Mario Sakamoto <mskamot@gmail.com>
	 * @see https://wtag.com.br/getz 
	 */
	 
	namespace src\logic;

	use lib\getz;	
	use src\logic;
	use src\model;	
	
	class DaoFactory extends getz\Dao {
	
		public function __construct($_DAO_FACTORY_IS_OFFICIAL) {
			parent::__construct(new logic\Connection($_DAO_FACTORY_IS_OFFICIAL));
		}

		/*
		 * Generated by Getz
		 */
		
	}
	
?>